version: "3.4"

services:
  mongo:
    image: 'bitnami/mongodb:4.4'
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - /var/data/mongodb
    environment:
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_DATABASE=${MONGODB_DATABASE}


  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
